### ISSUE TITLE
About min norm algorithm

### ISSUE THREAD

**Issue by liyangliu** [mit-gfx/ContinuousParetoMTL#1]
Hi, @PingchuanMa, @dut09,
I noticed that in this repo you borrowed codes from https://github.com/intel-isl/MultiObjectiveOptimization to solve the min-norm optimization problem. In the paper, it is solved as
![image](https://user-images.githubusercontent.com/5159489/88258768-73caa100-ccf3-11ea-96bc-e1aeded7288f.png)
However, in the code, I find it is implemented as a much more complicated process composed of the following four functions
![image](https://user-images.githubusercontent.com/5159489/88259090-31559400-ccf4-11ea-9acd-c3867838529b.png)
Do you mind giving a more detailed explanation about the relationship between the algorithm and the implementation? Thank you for your kind help in advance.

**Comment by PingchuanMa** [comment]
Hi @liyangliu. No, we don't, and we are happy that you asked such a good question. Each of these four functions serves for:
- `_min_norm_element_from2`: It solves for ![_min_norm_element_from2](https://render.githubusercontent.com/render/math?math=\gamma={\arg\min}_{0\le\gamma\le1}\left\lVert\gamma\mathbf{v}_1%2B(1-\gamma)\mathbf{v}_2\right\rVert_2) when ![v1v1](https://render.githubusercontent.com/render/math?math=\mathbf{v}_1\mathbf{v}_1), ![v1v2](https://render.githubusercontent.com/render/math?math=\mathbf{v}_1\mathbf{v}_2), and ![v2v2](https://render.githubusercontent.com/render/math?math=\mathbf{v}_2\mathbf{v}_2) are given. It corresponds to Algorithm 1 in their paper.
- `_min_norm_2d`: It's a wrapper of `_min_norm_element_from2`. It yields the ultimate solution for 2d problem or an initial guess for >2d problem.
- `_projection2simplex`: It projects a vector to a standard simplex by making the smallest change to it. In concrete, it solves for ![simplex](https://render.githubusercontent.com/render/math?math=\mathbf{e}={\arg\min}_{0\le\mathbf{e}\le1,\sum\mathbf{e}=1}\left\lVert\mathbf{v}-\mathbf{e}\right\rVert_2) when a vector ![v](https://render.githubusercontent.com/render/math?math=\mathbf{v}) is given.
- `_next_point`: It first transforms gradient direction to a zero-mean vector and then projects it to a standard simplex. It corresponds to line 10 and part of line 11 in Algorithm 2.

This file basically reflects how Algorithm 2 works but includes a few implementation details which make it hard to read. If it's a 2d problem, the analytic solution is returned without iterative solving. If it's an >2d problem, the initial guess is not exactly line 7 in Algorithm 2. Instead, the 2d solution is used for the initial guess. `dps` in [L106](https://github.com/mit-gfx/ContinuousParetoMTL/blob/master/pareto/optim/min_norm_solver.py#L106) is ![M](https://render.githubusercontent.com/render/math?math=\mathbf{M}) in line 8. Then [L121](https://github.com/mit-gfx/ContinuousParetoMTL/blob/master/pareto/optim/min_norm_solver.py#L121) computes ![et](https://render.githubusercontent.com/render/math?math=\mathbf{e}_\hat{t}). Then the following lines solve line 11 problem using `_min_norm_element_from2`. Finally, by applying line 12 or [L132](https://github.com/mit-gfx/ContinuousParetoMTL/blob/master/pareto/optim/min_norm_solver.py#L132), a new alpha is there. This process is run until converge or reaching an iteration limit. In the implementation, a few extra modifications for numerical stability are introduced, but not clearly commented in code or reflected in pseudo-code. We apologize for it.

We borrowed this implementation from [[Sener & Koltun, 2018]](https://github.com/intel-isl/MultiObjectiveOptimization). We kept it mostly original, which is intended for a fair comparison with other work ([[Lin et al., 2019]](https://github.com/Xi-L/ParetoMTL) also referred to it). There is much room to optimize this algorithm in time-cost performance, but it's not where our algorithm focuses. It turns out that Krylov subspace method is the key to efficiency in our method. Hope this resolves your question.

**Comment by liyangliu** [comment]
Thank you for your responses.
